version: '3.8'

services:
  db:
    image: mysql:8.0  # Updated image name for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dcg
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5  # Retry 5 times

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pavansai505/dcg-backend:latest  # Updated image name for backend
    ports:
      - "8080:8080"  # Host port 8080 mapped to container port 8080
    environment:
      SPRING_APPLICATION_NAME: backend
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dcg  # Connects to the db service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      db:
        condition: service_healthy  # Ensure backend starts after db is healthy

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: pavansai505/dcg-frontend:latest  # Updated image name for frontend
    ports:
      - "4200:80"  # Map container port 80 to host port 4200
