pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials' // Replace with your Docker Hub credentials ID
        DOCKER_IMAGE_TAG = "${env.BUILD_ID}"
        DOCKER_HUB_REPO = 'pavansai505/dcg' // Replace with your Docker Hub repository name
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean and Build Backend') {
            steps {
                dir('app/backend') {
                    script {
                        // Clean and build the Maven project
                        bat 'mvn clean'
                        bat 'mvn install'
                    }
                }
            }
        }

        stage('Build Docker Images') {
            parallel {
                stage('Build UI Image') {
                    steps {
                        dir('app/ui') {
                            script {
                                docker.build("${DOCKER_HUB_REPO}:ui-${DOCKER_IMAGE_TAG}", ".")
                            }
                        }
                    }
                }
                stage('Build Backend Image') {
                    steps {
                        dir('app/backend') {
                            script {
                                docker.build("${DOCKER_HUB_REPO}:backend-${DOCKER_IMAGE_TAG}", ".")
                            }
                        }
                    }
                }
            }
        }

        stage('Push Docker Images') {
            parallel {
                stage('Push UI Image') {
                    steps {
                        script {
                            docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                                docker.image("${DOCKER_HUB_REPO}:ui-${DOCKER_IMAGE_TAG}").push('latest')
                                docker.image("${DOCKER_HUB_REPO}:ui-${DOCKER_IMAGE_TAG}").push("${DOCKER_IMAGE_TAG}")
                            }
                        }
                    }
                }
                stage('Push Backend Image') {
                    steps {
                        script {
                            docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                                docker.image("${DOCKER_HUB_REPO}:backend-${DOCKER_IMAGE_TAG}").push('latest')
                                docker.image("${DOCKER_HUB_REPO}:backend-${DOCKER_IMAGE_TAG}").push("${DOCKER_IMAGE_TAG}")
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and Push successful!'
        }
        failure {
            echo 'Build or Push failed.'
        }
    }
}
