server:
  port: 8443  # Set your desired HTTPS port
  ssl:
    key-store: classpath:ssl/keystore.p12  # Use 'classpath:' if the keystore is in the resources directory
    key-store-password: password123  
    key-store-type: PKCS12  # Specify the type of the keystore
    key-alias: dcg  # Alias of the key in the keystore
